import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import { exec } from "child_process";
import util from "util";
import { Client } from "pg";
import { S3Client, ListBucketsCommand } from "@aws-sdk/client-s3";

const execPromise = util.promisify(exec);

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { action } = body;

    // 1. VERIFY LICENSE
    if (action === "verifyLicense") {
      const { purchaseCode } = body;
      const LICENSE_SERVER_URL = "https://aiclexdoccollection.vercel.app/api/verify";
      const verifyRes = await fetch(LICENSE_SERVER_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ purchaseCode, domain: "localhost" })
      });
      const verifyData = await verifyRes.json();
      if (!verifyRes.ok || !verifyData.valid) {
        return NextResponse.json({ error: verifyData.error || "Invalid Purchase Code" }, { status: 403 });
      }
      return NextResponse.json({ success: true, unlock_key: verifyData.unlock_key });
    }

    // 2. VERIFY DATABASE & CREATE TABLES
    if (action === "verifyDb") {
      const { dbUrl } = body;
      if (!dbUrl) return NextResponse.json({ error: "Database URL is required" }, { status: 400 });
      
      try {
        // Test Connection
        const client = new Client({ connectionString: dbUrl });
        await client.connect();
        await client.query('SELECT 1');
        await client.end();
        
        // Push Tables
        // (Note: Writing temporary env so prisma push uses it)
        const tempEnvPath = path.join(process.cwd(), ".env.temp");
        fs.writeFileSync(tempEnvPath, `DATABASE_URL="${dbUrl}"`);
        await execPromise("npx dotenv -e .env.temp -- npx prisma db push --accept-data-loss");
        fs.unlinkSync(tempEnvPath);

        return NextResponse.json({ success: true });
      } catch (e: any) {
        return NextResponse.json({ error: "Database connection failed: " + e.message }, { status: 400 });
      }
    }

    // 3. VERIFY STORAGE
    if (action === "verifyR2") {
      const { r2Access, r2Secret, r2Endpoint } = body;
      try {
        const s3Client = new S3Client({
          region: "auto",
          endpoint: r2Endpoint,
          credentials: { accessKeyId: r2Access, secretAccessKey: r2Secret },
        });
        await s3Client.send(new ListBucketsCommand({}));
        return NextResponse.json({ success: true });
      } catch (e: any) {
        return NextResponse.json({ error: "Storage credentials invalid: " + e.message }, { status: 400 });
      }
    }

    // 4. FINALIZE (Write .env and create admin logic)
    if (action === "finalize") {
      const { dbUrl, r2Access, r2Secret, r2Endpoint, r2Bucket, r2Public, unlockKey, authSecret, adminEmail, adminPassword } = body;
      
      const envContent = `
# AICLEX PORTAL - AUTOGENERATED CONFIG
AICLEX_UNLOCK_KEY="${unlockKey || ''}"
DATABASE_URL="${dbUrl}"
AUTH_URL="http://localhost:3000"
AUTH_TRUST_HOST=true
AUTH_SECRET="${authSecret || 'default_secret_please_change'}"
R2_ACCESS_KEY_ID="${r2Access || ''}"
R2_SECRET_ACCESS_KEY="${r2Secret || ''}"
R2_ENDPOINT="${r2Endpoint || ''}"
R2_BUCKET_NAME="${r2Bucket || ''}"
R2_PUBLIC_URL="${r2Public || ''}"
      `;

      const envPath = path.join(process.cwd(), ".env");
      fs.writeFileSync(envPath, envContent.trim());

      // Try to seed admin (assuming seed.ts exists)
      setTimeout(async () => {
         try {
             await execPromise("npx prisma db seed");
         } catch(e) {}
      }, 500);

      return NextResponse.json({ success: true });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });

  } catch (error: any) {
    console.error("Installation error:", error);
    return NextResponse.json({ error: "Internal Server Error during installation." }, { status: 500 });
  }
}
